
firebase_api_key = "AIzaSyCj0UPv444P-C6ggFZ8Q_NXvSSBraHeDG4"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true



[firebase_service_account]

type = "service_account"
project_id = "login1-e7ab2"
private_key_id = "c10287255d291fedc4120a0676344df5c564283d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQ9Bn2o5lCh00e
6r4Yfis8IJtD4X2vzEOaB6EAjT2hJ8G6wjLryUJerjRvuJ4M0TI0wpIENd1OITfM
BTvD8SRO8SlT7+c5my1ngYYpI0sVkasTJ4G93FGVZ7pmSJeEy5q7Pv//PqyocbTV
i1ws+9xDrT2VcGn5SrI9YV9ZwQjouJzX0w6zyOC17BGxpPb2WC8IJZ6g26DB9ORy
ff7pTSsO6NPg7I1g1zHnAAlWWeTfcE78TAPZf7GsBkJZ1zMxzjgndFiLne4YP9fl
t5eg99MxU8jXosAjFW6rMhHf5Fx+4V00luLxSaydricROdxWbPGuRKStqMsh2gVh
5ol4g+YVAgMBAAECggEAAPiJYFh9P05ioNilXnbDm6lpH0UecOEplT8g0+BUH3oQ
T95UHz1Vphv4GWbJsTSNn6ohxIw9hX3pBPUnRG9L5GQBdabhM6bRbLAw3+MOl8CQ
A2xFEY1DAcc0GgKPVaoeg201AkoXwkaY+P8HRBw9d0EITrfxfhuHPXrE1yVq9a3X
v7axKguNrr2xjH54zCPU/jgR5nXMM4qpUftGeZFem8D2pRTKwJ75PQFwHuoEqHh/
R59Ox3WTIrToSeSbx7hMhE5Qo9Zl3Q2WeTMaLRiGeShJzyO/EXtLs5CKN1YvNnKy
UNK250w6qXChYJhqiq+ZpXqBIXzkAk4u6KiyXAdzYQKBgQD/0cOpbOL5zwj8MdfF
mDlI/csDeOAQCrHpiGlLNyjtATFU+WroUqYLrE5oC/I6PRNqs11BChyR1/nOXhEh
vi0qz8db3Z54+ZBjanOHAed022rJ7Kgq9MpMEP8S2TNTLKNNOqbEUGhjruGAcp9A
YE0BLnmbtTwtSeYlq/So+bBKMQKBgQDRGd3lSahWeG+pTwWyUxUeU3GgLNxSozMf
XZmSnoPvw0CeZNPBSvRQtAeypljkp0bSh34v4SpLusp11S/ah1HTPphvT2J+aLW8
9l47VOk3gj+eS52CEqn7oE0+LyE7O56GFNDSiGM139dQQXUU8Ipuiph/8Gtbrph5
shKmS7O9JQKBgHEHIUgOUArHqtSiwQ8Qvt69I6GZGoZ78zeXic4txOtSh5Vfzhhv
y+WEb/AQtyl8KsQOE7nU2eKmZj0D2tXpzNMJkq/IL2iL+3uxYPHZqYY8G+azpWm1
VlxddhXB2ad6JXzN2TkLvdOtRP0Xp70tz1giTKC7Zqcr63/hhevSxk1BAoGBAI5o
iYFRKv7JQ3MRyJVslCN1PRuTsfHuCDFCdAcxQjYWynmVvcoVHFOiaOO4+y2u50MW
2FAPj9jHvH+H0/GG26l9JiAY9sGU2sF5ITBTYgpWALH0Wa9uuqoOwMyrGHzY29wB
bT8VeEwGyQN1sSGzuPQUHEx2Fwf33wxyxNTRFfapAoGAHIoWuC8NzhytmNsKHxQC
zVq596BLFqNEfVFx2ED663BAckmRbn5tiiDBREcasnDvX6SwFA7kwWoLJLfLzani
o5SCYF678tp9ICDlw1JOMecMskK+w/AQfiIMuPTy5nWt4OFv5zciYJ8spN5Y/cX0
tEQomwFDqzzvke872dafnck=
-----END PRIVATE KEY-----
"""

client_email = "firebase-adminsdk-fbsvc@login1-e7ab2.iam.gserviceaccount.com"
client_id = "109536071117363121755"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40login1-e7ab2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
