
firebase_api_key = "AIzaSyCj0UPv444P-C6ggFZ8Q_NXvSSBraHeDG4"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true



[firebase_service_account]

type = "service_account"
project_id = "login1-e7ab2"
private_key_id = "b4a1b46c20a9fcca473bb049beeb94859538596e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCVXJO2J6WHMu3C
61EQ/xeW3nh9BiVytmchQXJnlLdFTg9H047szwyFYw0vQc2gKYgIPuK4YF8NwRtk
m/BMMWsf+g4KkRRyGcSaSGEx1SSpPf4BkcAMKUh7he7SSn3TwFzD9tfjU+2zs3RM
LaIea9pMeCMyOiwuvYdwFB7ebCLG2zOVAjP2Rxn33tq4k2f8vPUVMsun1OSSzN92
lfReMuLJEOuFvlK4zqN6ZlMrcEhYwRsoto1i4Or2MSibTfgGf3VpLaUlTdsgWfNC
Lg3r5qJcDF2eMPQrSeHAyk770Vt7y37a1fWO2aPaF9jIp3+R8HGMCV/KayAtlK+h
s98RTTFtAgMBAAECggEAGyZQmFIVGeIFS4LcQb9owY0PcERzfqpOzUH5AoCLHs8t
YmQ/jOam80EZxq8KqlQaTMtniVXFOXoSWWOqFqN+AjpBHqUYBxSNgvDor/b7OsNQ
vmbItr0zVna2PmX5gMns4tcmD4W0Rc+3MliyKR74N6G33huqZ9WePp59rPcRjD1J
bPuBMAvpKbDXxz+vlYI4iELHfTOj2boYLHi4CyNCipqslHk1ACdJxtKLYYOWq0PA
C0QeB+Iw2+4EChRhPDiSt1XUyc6ei1GZIcFAqKBun+5Y6/2ADyFGs43KfutHI5hs
MM7puTJmu1iqQ8ktp9oV+JfhF/udx4mikJBAdc77uQKBgQDOmnjZaiovJLp4mGv5
tARvwashdWeZteoekEuGEzoWQFtFmm0N6GEpX1p9YBMiOA9ozwZxvIlmtL2fH6qq
8hkiOpCFrr5oedv6lk0WN/fqeYw9lz/EtNTRn0agZ3Pf/oqXxxDT/BFo5eB32t5s
aZWJM263F/Luil1WZSWt3Hp6JQKBgQC5EoU5WwX039TjfawNTYMEKH7oZ4Of1eL/
Vgyzoc9j2xcyNJR7v/n+VCMb/oU9O28spw7EwxL0S1xW9tsC7X83ckXO3m1FmUn+
mE3jrrrladOLomIg0fVEojR0RLgJyQZDHhUzXUf6BJPVzQ17mKpLPiB3F2bMPbTm
NZSk2emjqQKBgFP1sJDiNPxtl530i0SxpG/qK2pwdMahh+Ad0aNN4vgx9SWHCTRy
sDGI/5Qd3Ai28YQtRbgo30muv7SPwOKxegdP93VsOxLoGr5uICucWRKfjJ9m/NIq
jqYVbTU4dX2cyqO9kRgkwsp3SM5MUsGJ8uwLy716bQ4FisLWXgaWp+tFAoGAd+po
KCGyWlgtuLlVIcl3etpCYJOx1X7g9lDrKflOR4VOIlmvW/+oHAKoPRtNeb9o6aXV
C+jZ/zBVRIPupJb+Nw7z7HZylwYby7sjvMMalktbpr4wltNz+GShWDSuiqiWRibX
1dA7MuSEZaPXeJ4SuW4n2wJuuSfCbueIyMfpewECgYBQ8PzA6qgQXkBujqqZaX9l
x7Ux3+1kncadQh+sL4uPcogcG3ww3fjeFkJL9nxLOaq0mZeK5W+MSiOAFDpmrHjk
FwdRTiD4SzJO+QYP50up3ta0cW7vebytke6SxgA3GrT1O5P7wcWVxAon2C05rHiW
YWW9hUR1bqYZD6RM7iNwjg==
-----END PRIVATE KEY-----"""


client_email = "firebase-adminsdk-fbsvc@login1-e7ab2.iam.gserviceaccount.com"
client_id = "109536071117363121755"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40login1-e7ab2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
